services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: nta-website-cleaned-web-local
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      NODE_ENV: production
      DATABASE_URL: ${DATABASE_URL}
    restart: unless-stopped
